name: .NET

on:
  push:
    branches: [ healthcare_service ]
  pull_request:
    branches: [ healthcare_service ]

jobs:
  build:

    runs-on: Linux

    steps:
    - uses: actions/checkout@v2
      with: 
        token: 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
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
